### ISSUE TITLE
Вылетает при больших числах

### ISSUE THREAD

**Issue by dmittrj** [dragontino/Encoding#1]
Приложение аварийно завершает работу при вводе в поля чисел вроде 0.0000000000000000000000000000000000000000005

**Comment by dragontino** [comment]
Дмитрий, спасибо за вопрос! Я подставил ваше число в приложение, и все сработало корректно:

<img src="https://user-images.githubusercontent.com/89968445/194751490-8b9b965d-8045-4a04-93eb-3d36cb9f29a6.jpg" width=40% height=40%>
