### ISSUE TITLE
Нельзя ввести строку, целиком состоящую из пробелов

### ISSUE THREAD

**Issue by dmittrj** [dragontino/Encoding#11]
В режиме автоввода символов из текста если в строку ввести только пробелы, то приложение откажется вычислять коды символов

**Comment by dmittrj** [comment]
Не работает, даже если включить опцию «Учитывать пробелы»

**Comment by dragontino** [comment]
Исправлено в версии [1.4.1](https://github.com/dragontino/Encoding/releases/tag/v1.4)
