### ISSUE TITLE
Проблема с твердым знаком

### ISSUE THREAD

**Issue by dmittrj** [dragontino/Encoding#14]
В режиме автоввода символов из текста программа принимает „ъ“ за „Ь“, при этом „Ъ“ она верно принимает за „Ъ“

**Comment by dmittrj** [comment]
Аналогичная проблема с ё/Ё

**Comment by dragontino** [comment]
Действительно, работает некорректно. Будет исправлено в будущей версии. Спасибо)

**Comment by dragontino** [comment]
Исправлено в версии [1.4.1](https://github.com/dragontino/Encoding/releases/tag/v1.4)
