### ISSUE TITLE
Можно ввести одинаковые символы — 2

### ISSUE THREAD

**Issue by dmittrj** [dragontino/Encoding#17]
Несмотря на исправление, можно обойти скрипт, следящий за вводом различных символов. Для этого нужно проделать следующее:
1. Создать третий элемент
2. Ввести во все поля корректные символы и их вероятности (напр. а = 0.5, б = 0.4, в = 0.1). Важно! Символы должны быть строчными
3. Нажать на «Вычислить коды»
4. Убрать таблицу (смахнуть вниз)
5. Готово. Теперь можно, к примеру, поменять «б» на «в»

**Comment by dragontino** [comment]
Исправлено в версии [2.0.0](https://github.com/dragontino/Encoding/releases/tag/v2.0.0)
