### ISSUE TITLE
Программа не учитывает пробелы в режиме учитывания пробелов

### ISSUE THREAD

**Issue by dmittrj** [dragontino/Encoding#18]
Есть способ заставить программу не учитывать пробелы в режиме автоввода символов из текста. Для этого нужно ввести любой текст с пробелами (галочка «Учитывать пробелы» при этом должна быть снята), затем одновременно нажать на чекбокс «Учитывать пробелы» и кнопку «Вычислить коды». Теперь, даже если убрать таблицу (смахнуть вниз) и снова нажать на кнопку, программа не будет учитывать пробелы, хотя в данном случае чекбокс был честно установлен заранее, а не одновременно с нажатием на кнопку

**Comment by dragontino** [comment]
Ошибка исправлена в версии [1.4.2](https://github.com/dragontino/Encoding/releases/tag/v1.4)
