### ISSUE TITLE
Программа забывает текст после поворота девайса

### ISSUE THREAD

**Issue by dmittrj** [dragontino/Encoding#19]
Если в режиме автоввода символов из текста ввести любой текст в поле, а затем повернуть девайс на 90°, то текст не исчезнет, но кнопка вычисления кодов работать не будет (и продолжит не работать даже после возвращения правильной ориентации)

**Comment by dragontino** [comment]
Спасибо за помощь, ошибка будет исправлена в следующей версии. Пока что вы можете в этом случае нажать на текстовое поле и понажимать на кнопки клавиатуры. Тогда текст снова отобразится!

**Comment by dragontino** [comment]
Исправлено в версии [1.4.2](https://github.com/dragontino/Encoding/releases/tag/v1.4)
