### ISSUE TITLE
Баг, связанный с переключателями

### ISSUE THREAD

**Issue by dmittrj** [dragontino/Encoding#4]
Если произвести следующие действия:
1. Открыть Настройки
2. Включить «Автоввод символов из текста»
3. Включить «Использовать динамические цвета»
4. Нажать на системную кнопку «Назад» (приложение закрывается)
5. Открыть приложение
6. Открыть Настройки,

то переключатели оказываются заблокированы (при нажатии на них ничего не происходит)

**Comment by dmittrj** [comment]
P.S. Решение проблемы — закрыть приложение, выбросить его из оперативной памяти и открыть снова

**Comment by dragontino** [comment]
Исправлено в версии [1.2.1](https://github.com/dragontino/Encoding/releases/tag/v1.2.1)

**Comment by dragontino** [comment]
Исправлено в версии [1.4](https://github.com/dragontino/Encoding/releases/tag/v1.4)
