### ISSUE TITLE
Фактическая ошибка

### ISSUE THREAD

**Issue by dmittrj** [dragontino/Encoding#6]
На кнопке расчёта написано «Вычислить [...] по методу Фано», а должно быть «Вычислить [...] по методу Шеннона-Фано»

**Comment by dragontino** [comment]
Дмитрий, добрый день! Спасибо, что нашли ошибку! Действительно, алгоритм называется в честь двух ученых Клода Шеннона и Роберта Фано. Ошибка будет исправлена в следующем обновлении!

**Comment by dragontino** [comment]
Исправлено в версии [1.3](https://github.com/dragontino/Encoding/releases/tag/v1.3)
