### ISSUE TITLE
Ещё одна ошибка с не численными значениями

### ISSUE THREAD

**Issue by dmittrj** [dragontino/Encoding#9]
Если создать 3 поля, в два из них написать в качестве вероятности текстовую строку (из букв), а в третье поле написать 1, то приложение рассчитает коды (т.е. покажет таблицу при нажатии на кнопку), но в поле с кодом этого символа будет пусто, то есть программа не присвоила никакой код этому символу

**Comment by dragontino** [comment]
Исправлено в версии [1.3](https://github.com/dragontino/Encoding/releases/tag/v1.3)
